### PR TITLE
fix: response encode mismatch

### LINKED ISSUE #214: Encoding issue with old backup file
### Describe the bug

There have been reports that encoding errors occur after a major version upgrade if there is a backup from a previous version. When this symptom is present, get variant always returns with disabled.

### Steps to reproduce the bug

1. install unleash 5.1.1
2. make backup file with Unleash::Client.new
3. update unleash 6.0.8
4. Unleash::Client.new again

### Expected behavior

 no error

### Logs, error output, etc.

```bash
[2024/11/18 18:13:52]   INFO    [Unleash] ERROR: Error when sending report to unleash server. Server responded with http code 400.

---

[1] protodev 3.2.5-p208(main)> Rails.configuration.unleash = Unleash::Client.new
[Unleash] ERROR: Unable to save backup file. Exception thrown Encoding::UndefinedConversionError:'"\xE3" from ASCII-8BIT to UTF-8'
[Unleash] ERROR: stacktrace: ["/data/pksys/pokota/shared/bundle/ruby/3.2.0/gems/unleash-6.0.8/lib/unleash/toggle_fetcher.rb:65:in `write'" 
... 省略 ...

[4] protodev 3.2.5-p208(main)> FeatureToggle.new('ft0000_nextgen', User.find(187), nil, Time.zone.now, country).enabled
[Shard: main_r]  [pokota_protodev2016] replica User Load (2.4ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 187 LIMIT 1
[Shard: main_r]  [pokota_protodev2016] replica UserRankPoint Load (2.3ms)  SELECT `user_rank_points`.* FROM `user_rank_points` WHERE `user_rank_points`.`user_id` = 187 LIMIT 1
false
```

### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

_No response_

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

ruby 6.0.8

### PR DESCRIPTION
**Pull request by marocchino**
## About the changes

Ruby's file writing defaults to utf-8, but net http's response seems to be based on the header and ASCII is used by default when no specification is made.
I didn't write any test files, but I verified them as follows:

```
# run with main branch
bin/spring stop
bin/rails c
> Unleash::Client.new
[Unleash] ERROR: Unable to save backup file. Exception thrown Encoding::UndefinedConversionError:'"\xE3" from ASCII-8BIT to UTF-8'
...
# run with this branch
bin/spring stop
bin/rails c
> Unleash::Client.new
(no error)
```

Closes  #214

### CODE REVIEW

File: lib/unleash/util/http.rb [hunk 1]
```diff
@@ -24,6 +24,7 @@ def self.post(uri, body)
       def self.http_connection(uri)
         http = Net::HTTP.new(uri.host, uri.port)
         http.use_ssl = true if uri.scheme == 'https'
+        http.response_body_encoding = 'UTF-8'
```
Comment (marocchino) [inline lib/unleash/util/http.rb:27]: https://ruby-doc.org/3.2.5/stdlibs/net/Net/HTTP.html#method-i-request_post

**Comment by sighphyre** [comment]
Thanks for the fix, seems reasonable

**Review by sighphyre — APPROVED** [review]
LGTM
